### ISSUE TITLE
Align support

### ISSUE THREAD

**Issue by UXBox-Design** [gubbigubbi/kona-instagram#4]
I believe it's worth to add:

```
supports: {
    align: true
}
```

**Comment by gubbigubbi** [comment]
Whereabout would this be added? For what reason? Can you give me a brief explanation then you should be able to do a PR no probs

**Comment by UXBox-Design** [comment]
Huh... it was too big shortcut. I meant the gutenberg block alignment support (wide, full).
https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#supports-optional
I believe in /src/block/block.js.

It's good to give an option to users manage the width of block.

**Comment by gubbigubbi** [comment]
Ahhhh k,
Ill add it in next release :)
